PREFIX : <http://localhost:8001/base1/model1/>
PREFIX ktbs: <http://liris.cnrs.fr/silex/2009/ktbs#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    [ a :Session ;
      ktbs:hasBegin ?begin ;
      ktbs:hasBeginDT ?begindt ;
      ktbs:hasEnd ?end ;
      ktbs:hasEndDT ?enddt ;      
      ktbs:hasSourceObsel ?open, ?close ;
      :channel ?channel ;
      rdfs:label %(dummy)s
    ] .
} WHERE {
    ?open a :OpenChat ;
      ktbs:hasBegin ?begin ;
      ktbs:hasBeginDT ?begindt ;
      :channel ?channel .
    ?close a :CloseChat ;
      ktbs:hasEnd ?end ;
      ktbs:hasEndDT ?enddt ;      
      :onChannel ?open .
}
