package org.liris.ktbs.java.tests;

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;

public class JenaTests {
	public static void main(String[] args) {
		Model model = ModelFactory.createDefaultModel();
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property1"),
				model.getResource("http://mydomain/resource2/")
		);
		model.add(
				model.getResource("http://mydomain/resource1/"),
				model.getProperty("http://mydomain/property2"),
				model.getResource("http://mydomain/resource3/")
		);
		System.out.println("---------------------------------------------------");
		model.getWriter("TURTLE").write(model, System.out, "http://mydomain/");
		Model model2 = ModelFactory.createDefaultModel();
		model2.add(
				model2.getResource("http://mydomain/resource1/"),
				model2.getProperty("http://mydomain/property1"),
				model2.getResource("http://mydomain/resource2/")
		);
		model2.add(
				model2.getResource("http://mydomain/resource1/"),
				model2.getProperty("http://mydomain/property3"),
				model2.getResource("http://mydomain/resource4/")
		);
		System.out.println("---------------------------------------------------");
		model2.getWriter("TURTLE").write(model2, System.out, "http://mydomain/");
		System.out.println("---------------------------------------------------");
		Model union = model.union(model2);
		union.getWriter("TURTLE").write(union, System.out, "http://mydomain/");
		System.out.println("---------------------------------------------------");
		model.add(model2);
		model.getWriter("TURTLE").write(model, System.out, "http://mydomain/");
		System.out.println("---------------------------------------------------");
		
	}
}
